/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119192-gd073d0d3bb-20250409"
#endif /* AVUTIL_FFVERSION_H */
